Update buildapp.yml

diff --git a/.github/workflows/buildapp.yml b/.github/workflows/buildapp.yml
--- a/.github/workflows/buildapp.yml
+++ b/.github/workflows/buildapp.yml
@@ -5,7 +5,7 @@ on:
     inputs:
       sdk_version:
         description: "iOS SDK Version"
-        default: "17.5"
+        default: "16.5"
         required: true
         type: string
       decrypted_youtube_url:
@@ -55,6 +55,9 @@ jobs:
     permissions:
       contents: write
 
+    env:
+      THEOS: ${{ github.workspace }}/theos
+
     steps:
       - name: Checkout Main Repository
         uses: actions/checkout@v4
@@ -71,7 +74,7 @@ jobs:
           ref: main
 
       - name: Install Dependencies
-        run: brew install ldid dpkg make
+        run: brew install ldid dpkg make git
 
       - name: Download Theos
         uses: actions/checkout@v4
@@ -94,13 +97,18 @@ jobs:
       - name: Download iOS SDK
         if: steps.SDK.outputs.cache-hit != 'true'
         run: |
-          git clone -n --depth=1 --filter=tree:0 https://github.com/aricloverALT/sdks/
+          git clone -n --depth=1 --filter=tree:0 https://github.com/aricloverALT/sdks.git
           cd sdks
-          git sparse-checkout set --no-cone iPhoneOS${{ inputs.sdk_version }}.sdk
+          git sparse-checkout init --cone
+          git sparse-checkout set iPhoneOS${{ inputs.sdk_version }}.sdk
           git checkout
-          mv *.sdk $THEOS/sdks
-        env:
-          THEOS: ${{ github.workspace }}/theos
+          if ls iPhoneOS${{ inputs.sdk_version }}.sdk 1> /dev/null 2>&1; then
+            mv iPhoneOS${{ inputs.sdk_version }}.sdk $THEOS/sdks/
+            echo "SDK moved to $THEOS/sdks/"
+          else
+            echo "Error: iPhoneOS${{ inputs.sdk_version }}.sdk not found"
+            exit 1
+          fi
 
       - name: Download Theos Jailed
         uses: actions/checkout@v4
@@ -113,7 +121,7 @@ jobs:
       - name: Install Theos Jailed
         run: ./theos-jailed/install
         env:
-          THEOS: ${{ github.workspace }}/theos
+          THEOS: ${{ env.THEOS }}
 
       - name: Fix Compiling Environment
         run: |
@@ -131,7 +139,7 @@ jobs:
           cp ./libundirect.tbd $THEOS/lib/ || true
           ls -l $THEOS/lib
         env:
-          THEOS: ${{ github.workspace }}/theos
+          THEOS: ${{ env.THEOS }}
 
       - name: Hash YouTube IPA URL
         run: |
@@ -144,68 +152,28 @@ jobs:
           wget "$YOUTUBE_URL" --quiet --no-verbose -O main/YouTube.ipa
           unzip -q main/YouTube.ipa -d main/tmp
           echo "YT_VERSION=$(grep -A 1 '<key>CFBundleVersion</key>' main/tmp/Payload/YouTube.app/Info.plist | grep '<string>' | awk -F'[><]' '{print $3}')" >> $GITHUB_ENV
-          wget -qO- https://github.com/dayanch96/YTLite/releases/latest > main/tmp/release_page.html
-          YTLITE_VERSION=$(grep -o -E '/tag/v[^"]+' main/tmp/release_page.html | head -n 1 | sed 's/\/tag\/v//')
-          echo "YTLITE_VERSION=5.0.1" >> $GITHUB_ENV
           rm -rf main/tmp/Payload/YouTube.app/_CodeSignature/CodeResources
           rm -rf main/tmp/Payload/YouTube.app/PlugIns/*
-          python - <<EOF
-          import plistlib
-          def remove_uisupporteddevices(filepath):
-              with open(filepath, 'rb') as f:
-                  plist = plistlib.load(f)
-              if 'UISupportedDevices' in plist:
-                  del plist['UISupportedDevices']
-              with open(filepath, 'wb') as f:
-                  plistlib.dump(plist, f)
-          filepath = 'main/tmp/Payload/YouTube.app/Info.plist'
-          remove_uisupporteddevices(filepath)
-          EOF
           cp -R main/Extensions/*.appex main/tmp/Payload/YouTube.app/PlugIns
         env:
-          THEOS: ${{ github.workspace }}/theos
+          THEOS: ${{ env.THEOS }}
           YOUTUBE_URL: ${{ env.URL_YT }}
 
       - name: Build YTLitePlus Package
-        id: build_package
         run: |
-          cd ${{ github.workspace }}/main
-          sed -i '' "s/^BUNDLE_ID.*$/BUNDLE_ID = ${{ env.BUNDLE_ID }}/" Makefile
-          sed -i '' "s/^DISPLAY_NAME.*$/DISPLAY_NAME = ${{ env.APP_NAME }}/" Makefile
-          sed -i '' "s/^PACKAGE_VERSION.*$/PACKAGE_VERSION = ${{ env.YT_VERSION }}-5.0.1/" Makefile
+          cd main
+          sed -i '' "s/^BUNDLE_ID.*$/BUNDLE_ID = ${{ inputs.bundle_id }}/" Makefile
+          sed -i '' "s/^DISPLAY_NAME.*$/DISPLAY_NAME = ${{ inputs.app_name }}/" Makefile
           sed -i '' "s/^export TARGET.*$/export TARGET = iphone:clang:${{ inputs.sdk_version }}:14.0/" Makefile
           sed -i '' "s/^export SDK_PATH.*$/export SDK_PATH = \$(THEOS)\/sdks\/iPhoneOS${{ inputs.sdk_version }}.sdk\//" Makefile
           make package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1
-          mv "packages/$(ls -t packages | head -n1)" "packages/YTLitePlus_${{ env.YT_VERSION }}_5.0.1.ipa"
-          echo "package=$(ls -t packages | head -n1)" >> $GITHUB_OUTPUT
-          echo -e "==> \033[1mSHASUM256: $(shasum -a 256 packages/*.ipa | cut -f1 -d' ')\033[0m"
-          echo -e "==> \033[1mBundle ID: ${{ env.BUNDLE_ID }}\033[0m"
+          mv "packages/$(ls -t packages | head -n1)" "packages/YTLitePlus_${{ env.YT_VERSION }}.ipa"
         env:
-          THEOS: ${{ github.workspace }}/theos
-          BUNDLE_ID: ${{ inputs.bundle_id }}
-          APP_NAME: ${{ inputs.app_name }}
+          THEOS: ${{ env.THEOS }}
 
       - name: Upload Artifact
         if: ${{ inputs.upload_artifact }}
         uses: actions/upload-artifact@v4
         with:
-          name: YTLitePlus_${{ env.YT_VERSION }}_${{ env.YTLITE_VERSION }}
-          path: ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}
-          if-no-files-found: error
-
-      - name: Upload Artifact to Catbox
-        if: ${{ inputs.catbox_upload }}
-        run: |
-          RESPONSE=$(curl -F "reqtype=fileupload" -F "fileToUpload=@${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}" https://catbox.moe/user/api.php)
-          CATBOX_URL=$(echo $RESPONSE | grep -o -E 'https://files.catbox.moe/[^"]*')
-          echo "Uploaded artifact to $CATBOX_URL"
-          CATBOX_FILE=$(echo $CATBOX_URL | sed 's|https://files.catbox.moe/||')
-          echo "CATBOX_FILE=$CATBOX_FILE" >> $GITHUB_ENV
-          echo "CATBOX_URL=$CATBOX_URL" >> $GITHUB_ENV
-
-      - name: Prepare Release Notes
-        if: ${{ inputs.create_release }}
-        run: |
-          export TODAY=$(date '+%Y-%m-%d')
-          sed "s/%ytliteplus_version%/${{ env.YTLITE_VERSION }}/g; s/%youtube_version%/5.0.1/g; s/%catbox_url%/${{ env.CATBOX_FILE }}/g; s/%date%/$TODAY/g" \
-          main/.github/RELEASE_TEMPLATE/Release.md > ${{ github.workspace }}/release_notes.md
+          name: YTLitePlus_${{ env.YT_VERSION }}
+          path: ${{ github.workspace }}/main/packages/*.ipa
